---
variables:
  company: ACME Inc.
  company_short: ACME
  company_email: support@example.com
  product: Example App
  version: 8.18.0.0
  applauncher: "{{.linux_app_launcher}}"
  uninstaller_name: "{{.uninstaller_name}}"

default_install_dir_name: '{{.product | replace " " "" }}{{ index (.version | split ".") 0 }}'
start_command: ExampleApp
icon_file: ExampleApp.png

log_filename: installer.log

gui_css: |
  window, dialog, button, entry {
    background: #fff;
    color: #222;
  }
  textview {
    font-size: .7em;
  }
  textview text {
    color: #000;
    background: #f8f8f8;
  }
  entry.faint-text {
    color: #888;
  }
