---
variables:
  product: Example App
  version: 1.0
  company: ACME Inc.
  company_short: ACME
  company_contact: support@example.com
  applauncher: "{{.linux_app_launcher}}"
  uninstaller_name: "{{.uninstaller_name}}"
  start_command: ExampleApp.sh
  icon_file: ExampleApp.png

must_accept_license_on_cli: true

default_install_dir_name: '{{.product | replace " " "" }}{{ index (.version | split ".") 0 }}'

log_filename: installer.log

gui_css: |
  window, dialog, button, entry {
    background: #fff;
    color: #222;
  }
  textview {
    font-size: .7em;
  }
  textview text {
    color: #000;
    background: #f8f8f8;
  }
  entry.faint-text {
    color: #888;
  }
